name: prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prettier
        run: |
          yarn --frozen-lockfile
          yarn run format:github-action
